### ISSUE TITLE
Questions/Pods/Backend/Running

### ISSUE THREAD

**Issue by dubnationwarriors** [p0x6/spaced#10]
@p0x6 I just had a few questions, since I wanted to learn about your app and wanted to contribute. How did you guys make your backend and what tools/services are you using? (Ex: mongoDB, AWS ) In the app how are you calling the backend? Also, when I try running, I can't see the map or search up any places. I had to delete one of the pods, cause it wasn't working. I can blacklist locations, but that's it.

**Comment by p0x6** [comment]
Hey there! The backend is here. https://github.com/p0x6/spaced-backend

If you want to change can invite you to the project slack.

The app doesn't work because you need a .env file.

**Comment by dubnationwarriors** [comment]
@p0x6 I added a .env file with the with the map box api key, but the map isn't working. The blacklisting is though. Also, could I get an explanation on how the backend works, or at least a picture of how the mongodb and redis look like. It would also be great if you could invite me to the slack workspace. I removed this pod: pod 'NoUseFrameworks-MapboxMobileEvents',  :podspec => '../node_modules/@react-native-mapbox-gl/maps/ios/NoUseFrameworks-MapboxMobileEvents/NoUseFrameworks-MapboxMobileEvents.podspec.json'

**Comment by p0x6** [comment]
https://join.slack.com/t/spacedgroup/shared_invite/zt-d6n4ogs1-BvNB44Gtl7iG7t6UDTlWwA we can chat on here


On April 27, 2020 at 9:54 PM, dubnationwarriors (notifications@github.com) wrote:

I added a .env file with the with the map box api key, but the map isn't working. The blacklisting is though. Also, could I get an explanation on how the backend works.
